name = "websocket-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
# compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
# CloudFlare kindly asks to replace new_classes with new_sqlite_classes if on free plan
#new_classes = ["WebSocketServer"]
new_sqlite_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-chat"
database_id = "b7005a3e-8be9-4301-b1aa-1ff2f11d7fc8"

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
